# ====================================================================================
# Inputs and configuration

inputs:

  # ====================================================================================
  # 🗃️ Base content
  
  # Base content
  base:
    description: Metrics base content
    default: header, activity, community, repositories, metadata
  
  # Number of repositories to use to computes metrics
  # Using more will result in more accurate metrics, but you may hit GitHub rate-limit more easily if you use a lot of plugins
  repositories:
    description: Number of repositories to use
    default: 100
  
  # Number of repositories to load at once by queries
  # If you encounter GitHub queries timeouts, using a lower value here may solve issues
  repositories_batch:
    description: Number of repositories to load at once by queries
    default: 100
  
  # Include forked repositories into metrics
  repositories_forks:
    description: Include forks in metrics
    default: no
  
  # Filter repositories by user affiliations (you can specify multiple affiliations constraints)
  # Set to "" to use all repositories related to you
  # Note that it may affect some plugin outputs (broad affiliations will result in less representative metrics)
  repositories_affiliations:
    description: Repositories affiliations
    default: owner
  
  # List of default repositories that will be skipped
  # Plugins supporting a "skip repositories option" will automatically append repositories listed in this option
  repositories_skipped:
    description: Default repositories to skip
    default: ""
  
  # List of surnames or email addresses you use when authoring commits
  # These are mostly used to perform commits analysis to detect ownership
  commits_authoring:
    description: List of surnames or email addresses you use when authoring commits
    default: .user.login
  
  # ====================================================================================
  # 🧱 Core
  
  # User account personal token
  # No additional scopes are needed unless you want to include private repositories metrics
  # Some plugins may also require additional scopes
  # ────────────────────────────────────────────────────────────────
  # If you're only using plugins which don't really require a GitHub token, you may pass "NOT_NEEDED" as value
  token:
    description: GitHub Personal Token
    required: true
  
  # GitHub username
  # Defaults to "token" owner
  user:
    description: GitHub username
    default: ""
  
  # GitHub repository
  # Compute metrics for a repository instead ("user" being the repository owner)
  # Check https://github.com/lowlighter/metrics/blob/master/source/templates/repository/README.md for more informations
  repo:
    description: GitHub repository
    default: ""
  
  # Set to "github.token"or"{{ secrets.GITHUB_TOKEN }}"
  # GITHUB_TOKEN is a special auto-generated token restricted to current repository, which is used to push files in it
  committer_token:
    description: GitHub Token used to commit metrics
    default: ${{ github.token }}
  
  # Branch used to commit rendered metrics
  committer_branch:
    description: Branch used to commit rendered metrics
    default: ""
  
  # Commit message
  # Use "${filename}" to display filename
  committer_message:
    description: Commit message
    default: Update ${filename} - [Skip GitHub Action]
  
  # Instead of saving metrics to a repository, it's possible to save them to a gist to avoid "commits pollution"
  # Gist must be created prior and you must pass its identifier in the following option
  # Set "gist" in "output_action" to use this option
  committer_gist:
    description: Gist used to store metrics
    default: ""
  
  # Rendered metrics output path, relative to repository's root
  # When using "*", the correct extension will automatically on "config_output" value
  filename:
    description: Rendered metrics output path
    default: github-metrics.*
  
  # Rendered markdown output path (when using a markdown template)
  # It can be either a local path or a link (e.g. raw.githubusercontent.com)
  markdown:
    description: Rendered markdown output path
    default: TEMPLATE.md
  
  # Rendered markdown file cache (when using a markdown template)
  markdown_cache:
    description: Rendered markdown file cache
    default: .cache
  
  # Output action
  output_action:
    description: Output action
    default: commit
  
  # Optimize SVG image to reduce its filesize
  # Some templates may not support this option
  optimize:
    description: SVG optimization
    default: yes
  
  # Setup additional templates from remote repositories
  setup_community_templates:
    description: Additional community templates to setup
    default: ""
  
  # Template to use
  # To use community template, prefix its name with "@"
  template:
    description: Template to use
    default: classic
  
  # Additional query parameters (JSON string)
  # Some templates may require additional parameters which you can specify here
  # Do not use this option to pass plugins parameters as they'll be overwritten by the other options
  query:
    description: Additional query parameters
    default: "{}"
  
  # Define additional CSS that will be injected in used template
  # Example:
  # config_extras_css꞉ |
  #   h2 {
  #     color: red;
  #   }
  extras_css:
    description: Extra CSS
    default: ""
  
  # Timezone used by metrics
  # See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  config_timezone:
    description: Timezone used
    default: ""
  
  # Specify in which order metrics content will be displayed
  # If you omit some partials, they'll be appended at the end in default order
  # See "partials/_.json" of each template for a list of supported partials
  config_order:
    description: Configure content order
    default: ""
  
  # Use twemojis instead of emojis
  # May increase filesize but emojis will be rendered the same across all platforms
  config_twemoji:
    description: Use twemojis instead of emojis
    default: no
  
  # Render GitHub custom emojis (like ":octocat:", see full list at https://api.github.com/emojis)
  # May increase filesize
  config_gemoji:
    description: Use GitHub custom emojis
    default: yes
  
  # Render display width
  config_display:
    description: Render display width
    default: regular
  
  # Enable SVG CSS animations
  config_animations:
    description: SVG CSS animations
    default: yes
  
  # Configure padding for output image (percentage value)
  # It can be used to add padding to generated metrics if rendering is cropped or has too much empty space
  # Specify one value (for both width and height) or two values (one for width and one for height)
  config_padding:
    description: Image padding
    default: 0, 8 + 11%
  
  # Metrics output format
  config_output:
    description: Output image format
    default: auto
  
  # Number of retries in case rendering fail
  retries:
    description: Number of retries
    default: 3
  
  # Time to wait (in seconds) before each retry
  retries_delay:
    description: Time to wait (in seconds) before each retry
    default: 300
  
  # Throw on plugins errors
  # If disabled, metrics will handle errors gracefully with a message in rendered metrics
  plugins_errors_fatal:
    description: Die on plugins errors
    default: no
  
  # Debug mode
  # Note that this will automatically be enabled if job fails
  debug:
    description: Debug logs
    default: no
  
  # Ensure SVG can be correctly parsed after generation
  verify:
    description: Verify SVG
    default: no
  
  # Debug flags
  debug_flags:
    description: Debug flags
    default: ""
  
  # Dry-run mode (perform generation without output)
  # Unlike "output_action" set to "none", output file won't be available in "/metrics_renders"
  dryrun:
    description: Enable dry-run
    default: no
  
  # Experimental features
  experimental_features:
    description: Experimental features
    default: ""
  
  # Use mocked data to bypass external APIs
  use_mocked_data:
    description: Use mocked data instead of live APIs
    default: no
  
  # Use a pre-built image from GitHub registry when using unreleased versions of "lowlighter/metrics"
  # This option has no effect on forks (images will always be rebuilt from Dockerfile)
  # See https://github.com/users/lowlighter/packages/container/package/metrics for more information
  use_prebuilt_image:
    description: Use pre-built image from GitHub registry
    default: yes
  
  # Time to wait (in seconds) at the end of job
  # Use this to avoid triggering abuse mechanics on large workflows
  delay:
    description: Use this to avoid triggering abuse mechanics on large workflows
    default: 0
  
  # ====================================================================================
  # 📅 Isometric commit calendar
  
  # Enable or disable plugin
  plugin_isocalendar:
    description: Display an isometric view of your commits calendar
    default: no
  
  # Set time window shown by isometric calendar
  plugin_isocalendar_duration:
    description: Set time window shown by isometric calendar
    default: half-year

# ====================================================================================
# Action metadata
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

